### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by felix-hof** [crsuzh/ReplicationSuccess#78]
- [x] Add tests for all functions that ensure the output stays the same
 - [x] Implement tests for 'type = controlled' argument
 - [x] Include parameter space boundaries in tests everywhere
 - [x] Add R CMD INSTALL to makefile
 - [x] Check that we use the correct functions everywhere, i.e. use stats::p/q/d/r/-dist
